### ISSUE TITLE
Indicador de sessao para o usuario

### ISSUE THREAD

**Issue by LucasPacheko** [LucasPacheko/KuiperSettler#7]
Um elemento web para sinalizar a sessao do usuario.

**Comment by rafalm0** [comment]
Logica ta basicamente pronta mas a imagem nao ta sendo encontrada, nao soube direcionar/ organizar os diretorios corretamente

**Comment by LucasPacheko** [comment]
Olha, ficou top kkkk adorei

**Comment by LucasPacheko** [comment]
Acredito que resolvi
